/**
 * test
 * test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cat } from './cat';
import { Dog } from './dog';

export type InlineResponse200 = Cat | Dog;