/**
 * test
 * test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExtendedErrorModel } from './extendedErrorModel';
import { Message } from './message';
import { MyError } from './myError';

export interface Messages { 
    error?: Array<MyError>;
    success?: Array<Message>;
    info?: Array<Message>;
    extendedErrorModel?: any;
}